product_module.apicall:
  path: '/view'
  defaults:
    _controller: '\Drupal\product_module\Controller\ProductController::apiCall'
    _title: 'Api Data'
  requirements:
    _permission: 'access content'
    